pool: Hosted Windows 2019 with VS2019

trigger:
- master
- develop

variables:
  solution: 'Squirrel.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: self
  submodules: true

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 4.9.4

- task: NuGetCommand@2
  displayName: Restore
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: Build
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: Test
  inputs:
    testAssemblyVer2: |
     **\$(buildConfiguration)\*test*.dll
     !**\obj\**
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: NuGetCommand@2
  displayName: Pack
  inputs:
    command: pack
    packagesToPack: src\Squirrel.nuspec

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts
  inputs:
    pathtoPublish: '$(build.artifactStagingDirectory)'

- task: PublishSymbols@2
  displayName: Publish Symbols
  inputs:
    searchPattern: 'build\$(buildConfiguration)\**\*.pdb'
    publishSymbols: false
  continueOnError: true
